// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-semantic-scholar-api-key'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-finish';
